"""add_rejection_reason_and_subscription_plans

Revision ID: 5bc4a1e15321
Revises: 690994e9c80f
Create Date: 2026-05-28 15:24:28.848772

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5bc4a1e15321'
down_revision: str | None = '690994e9c80f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'old_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'new_value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_email_verification_otps_is_used'), table_name='email_verification_otps')
    op.drop_index(op.f('ix_inventory_transactions_product_id'), table_name='inventory_transactions')
    op.drop_constraint(op.f('inventory_transactions_tenant_id_fkey'), 'inventory_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_product_scan_logs_tenant_created_at'), table_name='product_scan_logs')
    op.drop_constraint(op.f('products_tenant_id_fkey'), 'products', type_='foreignkey')
    op.create_index(op.f('ix_stock_transfers_destination_warehouse_id'), 'stock_transfers', ['destination_warehouse_id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_product_id'), 'stock_transfers', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_source_warehouse_id'), 'stock_transfers', ['source_warehouse_id'], unique=False)
    op.add_column('tenants', sa.Column('rejection_reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'rejection_reason')
    op.drop_index(op.f('ix_stock_transfers_source_warehouse_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_product_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_destination_warehouse_id'), table_name='stock_transfers')
    op.create_foreign_key(op.f('products_tenant_id_fkey'), 'products', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_product_scan_logs_tenant_created_at'), 'product_scan_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_foreign_key(op.f('inventory_transactions_tenant_id_fkey'), 'inventory_transactions', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_inventory_transactions_product_id'), 'inventory_transactions', ['product_id'], unique=False)
    op.create_index(op.f('ix_email_verification_otps_is_used'), 'email_verification_otps', ['is_used'], unique=False)
    op.alter_column('audit_logs', 'new_value',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'old_value',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
