"""Add vector_chunks table for RAG

Revision ID: e2cc61f371e7
Revises: 20260602_0017
Create Date: 2026-06-03 16:28:17.226881

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'e2cc61f371e7'
down_revision: str | None = '20260602_0017'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vector_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vector_chunks_fst', 'vector_chunks', [sa.literal_column("to_tsvector('english', chunk_text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_vector_chunks_id'), 'vector_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_vector_chunks_source_id'), 'vector_chunks', ['source_id'], unique=False)
    op.create_index(op.f('ix_vector_chunks_source_type'), 'vector_chunks', ['source_type'], unique=False)
    op.create_index(op.f('ix_vector_chunks_tenant_id'), 'vector_chunks', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notifications_is_deleted'), 'notifications', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_is_deleted'), table_name='notifications')
    op.drop_index(op.f('ix_vector_chunks_tenant_id'), table_name='vector_chunks')
    op.drop_index(op.f('ix_vector_chunks_source_type'), table_name='vector_chunks')
    op.drop_index(op.f('ix_vector_chunks_source_id'), table_name='vector_chunks')
    op.drop_index(op.f('ix_vector_chunks_id'), table_name='vector_chunks')
    op.drop_index('ix_vector_chunks_fst', table_name='vector_chunks', postgresql_using='gin')
    op.drop_table('vector_chunks')
    # ### end Alembic commands ###
